### PR TITLE
Intial setup

### PR DESCRIPTION
**Pull request by esapir**
# Description

Updated the project files to allow running on the local environment.
I tackled three types of errors:

1. running 'npm install' failed because react, react-dom and react-redux versions were outdated
2. backend failed to start because MONGODB_URI environment variable have not been defined.
3. frontend failed to start because the default port was not set to 3001

Fixes:

1. Modified react, react-dom and react-redux version in frontend package.json
2. Added .env file in backend directory with default MONGO_URL
3. Added .env.local file in frontend directory with default PORT set to 3001

# How Has This Been Tested?

Tested using the following steps:
1. Cloned a new repository
2. Installed all dependencies
3. Run start.sh under root folder
4. Make sure frontend client is accessible under http://localhost:3001 and new user can be created

### CODE REVIEW

**Comment by vanessa-cooper** [comment]
Thanks @esapir, I'll review the changes right away.

**Review by vanessa-cooper — CHANGES_REQUESTED** [review]
.env file is usually not checked in to the repo because it might contain secrets. It's better to check in the template file (.env.template) and explain in the readme what it should contain.

**Comment by esapir** [comment]
I added .env.template files in both frontend and backend root directories.
I also modified readme files in both directories, guiding developers to use the template files to create .end.local files

**Review by vanessa-cooper — CHANGES_REQUESTED** [review]
It looks like we still have some problems. <br>To make it easier for new engineers to get the system up and running, is there a way you can make the readme file a bit more friendly?

**Review by vanessa-cooper — APPROVED** [review]
Awesome! Thanks so much for taking the time to make the setup experience a little smoother. Hopefully new engineers will now have a much easier start 🌟.
Now, all that’s left is to merge this PR, and the next item will be ready for you in Slack.

**Pull request merged**
